# Generated by Django 5.2.6 on 2025-09-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('SpecializationId', models.AutoField(primary_key=True, serialize=False)),
                ('SpecializationName', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.TextField(max_length=500)),
                ('HireDate', models.DateField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminbackendapi.role')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultationFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(choices=[('Available', 'available'), ('Not Available', 'not available')], default='Available', max_length=100)),
                ('YearsOfExperience', models.PositiveIntegerField(default=0)),
                ('Specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminbackendapi.specialization')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbackendapi.staff')),
            ],
        ),
    ]
